export const ACTION = {
  SET_NAME: "SET_NAME",
  ADD_QUESTION: "ADD_QUESTION",
  REMOVE_QUESTION: "REMOVE_QUESTION",
  ANSWER_QUESTION: "ANSWER_QUESTION",
  FINISH_ADDING_QUESTIONS: "FINISH_ADDING_QUESTIONS",
  APPROVE_ANSWERS: "APPROVE_ANSWERS",
  SYNC_RESPONSE: "SYNC_RESPONSE",
  SEND_RESULTS: "SEND_RESULTS",
};
